name: Setup PHP environment
description: Reusable action to avoid copy-pasting between workflows
inputs:
  composer-install:
    description: Install dependencies to teh pre-setup PHP environment
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.0'
        tools: 'composer:v2'
        coverage: none
      env:
        fail-fast: "true"

    - name: Install PHP deps
      if: ${{ inputs.composer-install }}
      shell: bash
      run: composer install
